translator:
  translation:
    text_size: 1500
    batch_size: 2000
    parts: 10
    separator: (S_0)
    exceptions_path: etc/exceptions.json
  current: llm
  clients:
    deeplx_api:
      api:
        url: http://localhost:1188/translate
        token: helloxxx
    llm:
      grpc:
        target: 127.0.0.1:50051
