# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/translation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/translation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/translation.proto\x12\x0btranslation\"\"\n\x12TranslationRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"#\n\x13TranslationResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2d\n\x12TranslationService\x12N\n\tTranslate\x12\x1f.translation.TranslationRequest\x1a .translation.TranslationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.translation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSLATIONREQUEST']._serialized_start=40
  _globals['_TRANSLATIONREQUEST']._serialized_end=74
  _globals['_TRANSLATIONRESPONSE']._serialized_start=76
  _globals['_TRANSLATIONRESPONSE']._serialized_end=111
  _globals['_TRANSLATIONSERVICE']._serialized_start=113
  _globals['_TRANSLATIONSERVICE']._serialized_end=213
# @@protoc_insertion_point(module_scope)
